### PR TITLE
Enable check.vv with parallel Suites

### PR DESCRIPTION
**Pull request by ewhamilton**

### CODE REVIEW

**Comment by vkamra** [comment]
💯

**Comment by tdmanv** [comment]
Nice! What is the impact on `c.Log`?

**Comment by ewhamilton** [comment]
Don't bother reviewing this yet-- it deadlocks.  At least I've now figured out how to debug go locally.

**Comment by ewhamilton** [comment]
First version had "issues".  New version supports `-check.vv -check.suitep N` and produces expected results without hang or panic.  Uses bytes.Buffer which is simple and should be sufficient.

Note for those interested:  io.Pipe has no buffering so sender blocks until there is a reader.  (But reader is waiting for channel from sender.  Ouch).  os.Pipe has buffering, but io.Copy blocks waiting for more data.

I included suitep_test.go that I used manually to debug and verify results.  It doesn't quite fit in here and should not be commited-- it has the wrong package and include lines and it doesn't have a way to automatically validate results.

**Comment by ewhamilton** [comment]
As far as `c.Log` goes, it gets buffered and then dumped to `os.Stdout` when the suite completes.

**Comment by ewhamilton** [comment]
@tdmanv I wonder whether we should allow tests to control whether or not their suites are run in parallel, regardless of the suitep setting.  And if so whether to opt in or out of parallelism.

Opt-in option would be to add a "allowParallel" boolean in RunConf and then add a `check.TestingParallel` or such (refactoring TestingT to a wrapper around core shared by both).

[ I imagine if we try to push this upstream this will be an area to rationalize with the parallel test support in testing itself.  Not sure we should spend the time digging into that for now.]

**Comment by tdmanv** [comment]
I think you're right - in order to get this upstream, we'll have to make the configuration clear and robust. I also like the idea of adding parameters to `TestingT()`, but I think it will be hard to merge upstream. I do suspect we'll have this fork for a while - upstream hasn't seen changes for some time.

I'd vote on merging as-is and using the current flags.

**Review by tdmanv — APPROVED** [review]

**Pull request merged**
